name: push
on:
  workflow_dispatch:
  push:
    branches:
       - master
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: tests
    env:
      CI: true
      SHA8: ${GITHUB_SHA::8}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ secrets.CACHE_NAME }}-build-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-${{ secrets.CACHE_NAME }}-build-
      - name: "Generate pot file"
        run: |
             pip install Babel
             pip install .
             wget -P spoonbill/locales/ ${{ secrets.SCHEME_URL }}
             pybabel extract -F babel.cfg . -o spoonbill/locales/base.pot
      - name: "Push source and download translate files from transifex"
        uses: docker://sergioisidoro/github-transifex-action:v0.2.0
        with:
            TX_TOKEN: ${{ secrets.TX_TOKEN }}
            git_flow: false
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pull_translations: true
            pull_sources: false
            push_translations: false
            push_sources: true
      - run: |
              sudo chown $(whoami) -R  spoonbill/locales/
              pip install --upgrade setuptools wheel
              pybabel compile -f -D spoonbill -d spoonbill/locales/
      - run: |
              python setup.py sdist bdist_wheel
              ls -la
